name: mirror-container-registry

on:
  push:
    paths:
      - 'mirror-container-registry/**'
  pull_request:
    paths:
      - 'mirror-container-registry/**'
  workflow_dispatch:

jobs:
  mirror-container-registry:
    uses: ./.github/workflows/_build-and-upload.yml
    with:
      module: mirror-container-registry
    secrets: inherit
