name: vault-secret-sync

on:
  push:
    paths:
      - 'vault-secret-sync/**'
  pull_request:
    paths:
      - 'vault-secret-sync/**'
  workflow_dispatch:

jobs:
  vault-secret-sync:
    uses: ./.github/workflows/_build-and-upload.yml
    with:
      module: vault-secret-sync
    secrets: inherit
